dist: trusty
language: cpp

notifications:
  email:
    recipients:
      - 0f9234u9f0jw3@gmx.de
    on_success: always
    on_failure: always

addons:
  apt:
    update: true
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0
    packages:
      ["libboost-all-dev", "doxygen", "libgraphicsmagick3", "libssl-dev", "libpq-dev", "libssl-dev", "libfcgi-dev"]

compiler: clang
os: linux

jobs:
  include:
    # GCC 7
    - env: CXX=g++-7 CC=gcc-7
      compiler: gcc
      addons: &gcc7
        apt:
          packages: ["g++-7",     "g++-7-multilib",   "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386"]
          sources: *apt_sources

    # GCC 8
    - env: CXX=g++-8 CC=gcc-8
      compiler: gcc
      addons: &gcc8
        apt:
          packages: ["g++-8",     "g++-8-multilib",   "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386"]
          sources: *apt_sources

    # GCC 9
    - env: CXX=g++-9 CC=gcc-9
      compiler: gcc
      addons: &gcc9
        apt:
          packages: ["g++-9",     "g++-9-multilib",   "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386"]
          sources: *apt_sources

before_install:
  - set -e
  - CMAKE_VERSION=3.19.3
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      echo CMAKE_URL=${CMAKE_URL}
      mkdir cmake-${CMAKE_VERSION} && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-${CMAKE_VERSION}
      export PATH=${PWD}/cmake-${CMAKE_VERSION}/bin:${PATH}
    fi
    cmake --version

script:
  # Debug
  - echo "Debug"
  - ./build.sh --build_type=Debug
  - printf "\n\n"
  # Release
  - echo "Release"
  - ./build.sh --build_type=Release

